### ISSUE TITLE
The kubeconfig generated is missing the region argument

### ISSUE THREAD

**Issue by bryantbiggs** [pulumi/pulumi-eks#1038]
### What happened?

I am trying to construct a Kubernetes provider thats suitable for deploying Helm charts onto an EKS cluster. However, I am getting a `cluster not found` error because the kubeconfig generated by the Pulumi EKS provider does not contain the region flag

### Example

Use this projects https://github.com/pulumi/pulumi-eks/tree/master/examples/aws-go-eks-helloworld example and inspect the generated kubeconfig - you will see it does not contain the `--region <region>` argument

### Output of `pulumi about`

x

### Additional context

This is what the `aws eks update-kubeconfig --name <name>` command generates

``` yaml
# truncated for brevity
exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - <region>
      - eks
      - get-token
      - --cluster-name
      - <name>
      - --output
      - json
      command: aws
```

And this is what the Pulumi kubeconfig generates:

``` yaml
# truncated for brevity
exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - <name>
      command: aws
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
