### ISSUE TITLE
Github action for up/preview/refresh... fails with 401 could not find latest version for provider eks

### ISSUE THREAD

**Issue by gio-pcb** [pulumi/pulumi-eks#1125]
### What happened?

I am using pulumi/eks as part of my infra deployment.

When running a pulumi stack action from gh (selfhosted) always fails with error 401.

```
      - name: Pulumi up
        if: ${{ github.event.inputs.pulumi_action == 'up' }}
        uses: pulumi/actions@v4
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_DEV_CONFIG_PASSPHRASE }}
        with:
          work-dir: infra
          cloud-url: s3://xxx
          stack-name: infra
          command: up
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

I can workaround this by adding a previous step to the workflow as follows:

```
      - name: Pulumi plugin install
        run: pulumi plugin install resource eks v1.0.4
        working-directory: src/infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Example

```
  Diagnostics:
    pulumi:providers:eks (default):
      error: could not find latest version for provider eks: 401 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-eks/releases/latest
```

### Output of `pulumi about`

v3.111.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
