### ISSUE TITLE
Empty preview step on tests is proposing changes that are not expected

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#199]
After the initial update of the [`replace-cluster-add-subnets`](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/examples/tests/replace-cluster-add-subnets/index.ts) test, the empty preview step is being shown changes even though it should not:

- See the `templateBody` of the ASG being [planned](https://gist.github.com/metral/8c756d45f90ceebeffde23860dc7c53d#file-log-txt-L1730) for an update.
- See the empty preview step erroring as changes are being [proposed](https://gist.github.com/metral/8c756d45f90ceebeffde23860dc7c53d#file-log-txt-L2208) when not expected.

e.g. here is a sample of the changes being proposed from a run of another test, the [`migrate-nodegroups`](https://github.com/pulumi/pulumi-eks/tree/master/nodejs/eks/examples/tests/migrate-nodegroups/index.ts), also hitting this change proposal for `templateBody`:

![image](https://user-images.githubusercontent.com/1112768/62639251-05c77700-b8f4-11e9-8e61-7e593867cdbc.png)

**Comment by metral** [comment]
https://s3-us-west-2.amazonaws.com/eng.pulumi.com/travis-logs/pulumi/pulumi-eks/834.1/failed-tests.tar.gz

**Comment by metral** [comment]
Another run of CI hit this same issue again, showing a proposed change for the `templateBody` of the CFStack, when the code was not touched: https://gist.github.com/metral/60aff5b74d7cafa980cee56403853151#file-log-txt-L1502

**Comment by metral** [comment]
Seems related:
- https://github.com/pulumi/pulumi-aws/issues/684#issuecomment-519199905
- https://github.com/pulumi/pulumi-terraform/pull/444

**Comment by metral** [comment]
Full output logs `-v=10`: [command-output.tar.gz](https://github.com/pulumi/pulumi-eks/files/3479183/command-output.tar.gz).

Note the changes in `VPCZoneIdentifier` from 4 subnets to 2 in the planned Diff of ` command-output/pulumi-preview-empty.20190807-145341.daef9.log`:

```
18331 provider_plugin.go:572] Provider[aws, 0xc0004cfaa0].Diff(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-standard-nodes,arn:aws:cloudformation:us-west-2:153052954103:stack/migrate-nodegroups-ng-standard-df8d4dab/79b171c0-b95d-11e9-94a6-067      37af08cb6) success: changes=2 #replaces=[] #stables=[onFailure name disableRollback timeoutInMinutes] delbefrepl=false, diffs=#[templateBody], detaileddiff=map[templateBody:kind:UPDATE ]
12318 I0807 14:53:39.954061   18331 step_generator.go:461] Planner decided to update 'urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-standard-nodes' (oldprops=map[__defaults:{[]} name:{migrate-nodegroups-ng-standard-df8d4dab} tags:{map[Name:{migrate-nodegroups-ng-standard-n      odes} __defaults:{[]}]} templateBody:{
12319                 AWSTemplateFormatVersion: '2010-09-09'
12320                 Outputs:
12321                     NodeGroup:
12322                         Value: !Ref NodeGroup
12323                 Resources:
12324                     NodeGroup:
12325                         Type: AWS::AutoScaling::AutoScalingGroup
12326                         Properties:
12327                           DesiredCapacity: 3
12328                           LaunchConfigurationName: migrate-nodegroups-ng-standard-nodeLaunchConfiguration-93e2d38
12329                           MinSize: 3
12330                           MaxSize: 10
12331                           VPCZoneIdentifier: ["subnet-0ee3176e3cf1f57ad","subnet-0600768622fca39b4","subnet-0eb02d2044415fff7","subnet-0479a9bdc91f0ddad"]
12332                           Tags:
12333
12334                           - Key: Name
12335                             Value: migrate-nodegroups-eksCluster-f4a345b-worker
12336                             PropagateAtLaunch: 'true'
12337                           - Key: kubernetes.io/cluster/migrate-nodegroups-eksCluster-f4a345b
12338                             Value: owned
12339                             PropagateAtLaunch: 'true'
12340                         UpdatePolicy:
12341                           AutoScalingRollingUpdate:
12342                             MinInstancesInService: '1'
12343                             MaxBatchSize: '1'
12344                 }] inputs=map[__defaults:{[]} name:{migrate-nodegroups-ng-standard-df8d4dab} tags:{map[Name:{migrate-nodegroups-ng-standard-nodes} __defaults:{[]}]} templateBody:{
12345                 AWSTemplateFormatVersion: '2010-09-09'
12346                 Outputs:
12347                     NodeGroup:
12348                         Value: !Ref NodeGroup
12349                 Resources:
12350                     NodeGroup:
12351                         Type: AWS::AutoScaling::AutoScalingGroup
12352                         Properties:
12353                           DesiredCapacity: 3
12354                           LaunchConfigurationName: migrate-nodegroups-ng-standard-nodeLaunchConfiguration-93e2d38
12355                           MinSize: 3
12356                           MaxSize: 10
12357                           VPCZoneIdentifier: ["subnet-0ee3176e3cf1f57ad","subnet-0600768622fca39b4"]
12358                           Tags:
12359
12360                           - Key: Name
12361                             Value: migrate-nodegroups-eksCluster-f4a345b-worker
12362                             PropagateAtLaunch: 'true'
12363                           - Key: kubernetes.io/cluster/migrate-nodegroups-eksCluster-f4a345b
12364                             Value: owned
12365                             PropagateAtLaunch: 'true'
12366                         UpdatePolicy:
12367                           AutoScalingRollingUpdate:
12368                             MinInstancesInService: '1'
12369                             MaxBatchSize: '1'
12370                 }]
12371 I0807 14:53:39.954102   18331 plan_executor.go:142] planExecutor.Execute(...): incoming event (nil? false, <nil>)
12372 I0807 14:53:39.954112   18331 plan_executor.go:224] planExecutor.handleSingleEvent(...): received RegisterResourceEvent
12373 I0807 14:53:39.954131   18331 registry.go:146] GetProvider(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::pulumi:providers:aws::default_0_18_26::ae7273b7-36d6-4b22-813f-0592ae1547c9)
12374 I0807 14:53:39.954148   18331 provider_plugin.go:424] Provider[aws, 0xc0004cfaa0].Check(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-2xlarge-nodes) executing (#olds=4,#news=3
12375 I0807 14:53:39.954157   18331 rpc.go:69] Marshaling property for RPC[Provider[aws, 0xc0004cfaa0].Check(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-2xlarge-nodes).olds]: __defaults={[]}
12376 I0807 14:53:39.954169   18331 rpc.go:69] Marshaling property for RPC[Provider[aws, 0xc0004cfaa0].Check(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-2xlarge-nodes).olds]: name={migrate-nodegroups-ng-2xlarge-eca6a7bd}
12377 I0807 14:53:39.954176   18331 rpc.go:69] Marshaling property for RPC[Provider[aws, 0xc0004cfaa0].Check(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-2xlarge-nodes).olds]: tags={map[Name:{migrate-nodegroups-ng-2xlarge-nodes} __defaults:{[]}]}
12378 I0807 14:53:39.954187   18331 rpc.go:69] Marshaling property for RPC[Provider[aws, 0xc0004cfaa0].Check(urn:pulumi:p-it-argon-migrate-no-42244f66::migrate-nodegroups::eks:index:NodeGroup$aws:cloudformation/stack:Stack::migrate-nodegroups-ng-2xlarge-nodes).olds]: Name={migrate-nodegroups-ng-2xlarge-nodes}
```

/cc @pgavlin @lukehoban thoughts?

**Comment by lukehoban** [comment]
@metral Have you been able to reproduce this locally outside of the test harness by following similar steps?   This would be easier to investigate with a repro.

I tried to take the test case in question `replace-cluster-add-subnets `, deploy it, and the run an empty preview.  I did this 5 times and never saw any changes proposed.

I actually can't tell from the notes above whether this is the same steps that you believe are triggering this in CI, or whether there is a more involved set of steps that are leading to this.

I'm also generally confused by many of the notes above.  The test  explicitly creates a VPC with only 3 public subnets and then deploys the cluster using 2 of the 3.  I have no idea where the snippet you show above is ever coming up with 4 subnets - that doesn't even seem physically possible using the example in question here.

**Comment by lukehoban** [comment]
> Note that awsx.ec2.Vpc.numberOfAvailabilityZones is not set, so it defaults to 2. And we're in us-west-4 that has 4 AZ's, and we create 1 private and 1 public in each of the AZ's, so we have 4 subnets: 2 private and 2 public.

I do not follow this - especially since (a) this example uses `awsx.Network` which creates only public subnets by default and (b) it explicitly requests only 3 AZs.

**Comment by lukehoban** [comment]
Oh - I guess I was confused as the examples in this issue shift between two different test cases.  I think the references to 4 subnets are all related to `migrate-nodegroups`?

**Comment by metral** [comment]
> I'm also generally confused by many of the notes above. The test explicitly creates a VPC with only 3 public subnets and then deploys the cluster using 2 of the 3. I have no idea where the snippet you show above is ever coming up with 4 subnets - that doesn't even seem physically possible using the example in question here.

Sorry for the lack of clarity. The 4 subnets was in ref to the `migrate-nodegroup` not the `replace-subnets`, as it creates 1 private and 1 public in the 2 AZs, for 4 total.

> I do not follow this - especially since (a) this example uses awsx.Network which creates only public subnets by default and (b) it explicitly requests only 3 AZs

Also intended for the `migrate-nodegroup`.

The repro is just running both `replace-cluster-add-subnets` and `migrate-nodegroups` locally.

I'm running a series of test on the most recent v0.18.10 master to see if this is even possible since I have not seen the error today, and will update with more clarity if necessary.

**Comment by lukehoban** [comment]
Got it. 

I was unable to repro against `replace-cluster-add-subnets`.  I'll take a look at `migrate-nodegroups` as well.

**Comment by metral** [comment]
On 10 runs of the both tests, `replace-cluster-add-subnets` failed twice with this error. This time interestingly enough, one of the failed runs went from 1 subnet to 2 on the empty preview step:

![image](https://user-images.githubusercontent.com/1112768/62756670-7a520100-ba2d-11e9-9339-33d542a080d0.png)

**Comment by lukehoban** [comment]
Do you have copies of the checkpoints before and after this error?

What exact set of stack operations are leading to this when it happens?

> went from 1 subnet to 2

It should never have been possible to end up deploying only 1 subnet with this test. The key question is really how you managed to get a deployment with only 1 subnet in the first place.

**Comment by metral** [comment]
> Do you have copies of the checkpoints before and after this error?

No, since I was running `make test_all` with only those 2 tests enabled, and the tests don't save state.

> It should never have been possible to end up deploying only 1 subnet with this test.

Agreed, this is odd. I'll look into running more tests with checkpoints being saved in between each step.

**Comment by metral** [comment]
@lukehoban here is the command output for the `replace-cluster-add-subnet` test that hits this `templateBody` diff `UPDATE` issue with the subnets. I ran this test only locally, with the other tests and examples commented out, across 5 runs and 1 managed to produce it.

envars set:

```
export AWS_REGION=us-west-2
export TF_LOG=TRACE
export PULUMI_TEST_DEBUG_LOG_LEVEL=9
export PULUMI_TEST_DEBUG_UPDATES=true
```

[replace-cluster-add-subnet-command-output.tar.gz](https://github.com/pulumi/pulumi-eks/files/3523336/replace-cluster-add-subnet-command-output.tar.gz)

**Comment by metral** [comment]
Additional output from a failed CI job yesterday for the `replace-cluster-add-subnet` test:

https://s3-us-west-2.amazonaws.com/eng.pulumi.com/travis-logs/pulumi/pulumi-eks/964.1/failed-tests.tar.gz

This time, unlike the usual failed runs of this test, goes from using 1 subnet to 2 subnets, whereas other failed runs usually propose less subnets to use:

```
Resources:
        NodeGroup:
                Type: AWS::AutoScaling::AutoScalingGroup
                Properties:
                        DesiredCapacity: 2
                        LaunchConfigurationName: test-replace-cluster-add-subnets-nodeLaunchConfiguration-da70d18
                        MinSize: 1
                        MaxSize: 2
                        VPCZoneIdentifier: ["subnet-0161c3fc1520e5f57"]
                        Tags:

                        - Key: Name
                        Value: test-replace-cluster-add-subnets-eksCluster-52a59d5-worker
                        PropagateAtLaunch: 'true'
                        - Key: kubernetes.io/cluster/test-replace-cluster-add-subnets-eksCluster-52a59d5
                        Value: owned
                        PropagateAtLaunch: 'true'
                UpdatePolicy:
                        AutoScalingRollingUpdate:
                        MinInstancesInService: '1'
                        MaxBatchSize: '1'
}] inputs=map[__defaults:{[]} name:{test-replace-cluster-add-subnets-defe117e} tags:{map[Name:{test-replace-cluster-add-subnets-nodes} __defaults:{[]}]} templateBody:{
AWSTemplateFormatVersion: '2010-09-09'
Outputs:
        NodeGroup:
                Value: !Ref NodeGroup
Resources:
        NodeGroup:
                Type: AWS::AutoScaling::AutoScalingGroup
                Properties:
                        DesiredCapacity: 2
                        LaunchConfigurationName: test-replace-cluster-add-subnets-nodeLaunchConfiguration-da70d18
                        MinSize: 1
                        MaxSize: 2
                        VPCZoneIdentifier: ["subnet-0161c3fc1520e5f57","subnet-03a3c1bb5eee25f16"]
                        Tags:
```

envvars set in CI:

```
export AWS_REGION=us-west-2
export PULUMI_TEST_DEBUG_LOG_LEVEL=9
export PULUMI_TEST_DEBUG_UPDATES=true
```
