### ISSUE TITLE
cluster-autoscaler helm chart auth fail on first attempt + false negative failure on ingress

### ISSUE THREAD

**Issue by jakegibson** [pulumi/pulumi-eks#437]
### Problem description

I've migrated a terraform project to Pulumi.  It is working but I'm running into two issues.  
1. cluster-autoscaler deployed via helm fails on initial deploy and I have to export the kubeconfig the initial deploy created and set it as my default then run again.  

2. Pulumi never fully reports a success because it hangs on `Ingress .status.loadBalancer field was not updated with a hostname/IP address`.  Even though it is not needed.  Using ALB -> to Traefik NodePort.  I've read issue #277 and tried applying but haven't gotten it to work, and again for my case isn't needed and I've tested the setup is working.  I didn't write the original terraform project and am new to kubernetes so forgive any naive errors/assumptions.  Here are probably the most relevant snippets.   I only added providerCredentialOpts to the cluster because I was getting an error 'could not load config() profile' even though I have a default defined 

- Other: <DETAILS>

### Errors & Logs
1. cluster unreachable from cluster-autoscaler intial deploy
2. Ingress .status.loadBalancer field was not updated with a hostname/IP address.
```
const profileName = 'terraform-dev'
const awsProvider = new aws.Provider('aws-provider', {
  profile: profileName,
  region: aws.getRegion().name
})
const kubeconfigOpts = { profileName: profileName }
const cluster = new eks.Cluster(config.serviceName, {
  vpcId: vpc.id,
  name: 'rpa-service',
  publicSubnetIds: vpc.publicSubnetIds,
  privateSubnetIds: vpc.privateSubnetIds,
  instanceType: 't2.medium',
  desiredCapacity: 2,
  minSize: 1,
  maxSize: 4,
  skipDefaultNodeGroup: true,
  createOidcProvider: true,
  providerCredentialOpts: kubeconfigOpts,
  instanceRoles: [role],
  // extraNodeSecurityGroups: [sg.id],
  tags: { Name: 'rpa-service' }
})
const clusterOidcProvider = cluster.core.oidcProvider
const clusterOidcProviderUrl = clusterOidcProvider.url
const kubeconfig = cluster.kubeconfig
const autoscalerAssumeRolePolicy = pulumi
  .all([clusterOidcProviderUrl, clusterOidcProvider.arn, autoscalerNamespace])
  .apply(([url, arn, namespace]) =>
    aws.iam.getPolicyDocument({
      statements: [
        {
          actions: ['sts:AssumeRoleWithWebIdentity'],
          conditions: [
            {
              test: 'StringEquals',
              values: ['owned'],
              variable: `autoscaling:ResourceTag/kubernetes.io/cluster/${config.clusterName}`
            },
            {
              test: 'StringEquals',
              values: ['true'],
              variable: `autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled`
            }
          ],
          effect: 'Allow',
          principals: [
            {
              identifiers: [arn],
              type: 'Federated'
            }
          ]
        }
      ]
    })
  )
const autoscalerRole = new aws.iam.Role('cluster-autoscaler', {
  assumeRolePolicy: autoscalerAssumeRolePolicy.json
})
new aws.iam.RolePolicyAttachment('autoscaler-role-attach-policy', {
  policyArn: autoscalerPolicy.arn,
  role: autoscalerRole.name
})
const managedNodeGroup = eks.createManagedNodeGroup(
  'rpa-ng',
  {
    cluster: cluster,
    nodeGroupName: 'aws-managed-ng1',
    nodeRoleArn: role.arn,
    labels: { ondemand: 'true', Environment: 'development' }
    // tags: {},
  },
  cluster
)
const autoscalerNamespaceName = autoscalerNamespace.metadata.apply(
  (m) => m.name
)
// Export the Namespace name
const namespaceName = ns.metadata.apply((m) => m.name)
// console.log('cluster', cluster.eksCluster, cluster.eksCluster.id.toString())
// Export the cluster's kubeconfig.
const clusterNodeInstanceRoleName = cluster.instanceRoles.apply(
  (roles) => roles[0].name
)


//primary service along with traefik dep
const rpaService = new k8s.helm.v3.Chart(
  config.serviceName,
  {
    path: './helm/rpa-service',
    name: 'rpa-service',
    values: {
      name: 'rpa-service',
      replica_count: 1,
      hostname: 'rpa.atmcdev.com',
      image_pull_policy: 'Always',
      image: managerUrl,
      workers: {
        idle_count: 2,
        prefix: 'rpa-worker',
        port: 3000,
        image: workerUrl
      },
      service: {
        type: 'ClusterIP',
        port: 8080
      },
      traefik: {
        providers: {
          kubernetes: {
            kubernetesIngress: {
              publishedService: `default/rpa-service-traefik`
            }
          }
        },

        service: {
          enabled: true,
          type: 'NodePort'
        },
        ports: {
          web: {
            nodePort: 32010
          }
        },
        image: {
          name: 'traefik',
          tag: '2.2.2'
        },
        additionalArguments: ['--log.level=INFO'],
        rbac: {
          enabled: true
        },
        accessLogs: {
          enabled: true
        },
        dashboard: {
          enabled: true
        }
      }
    }
  },
  { providers: { kubernetes: cluster.provider } }
)

// autoscaling group
const autoscaler = new k8s.helm.v3.Chart('autoscaler', {
  namespace: autoscalerNamespaceName,
  name: managedNodeGroup.resources[0].autoscalingGroups[0].apply(
    (asg) => asg.name
  ),
  chart: 'cluster-autoscaler',
  fetchOpts: {
    repo: 'https://kubernetes-charts.storage.googleapis.com/'
  },
  version: '7.3.4',
  values: {
    cloudProvider: 'aws',
    rbac: {
      serviceAccount: {
        annotations: {
          'eks.amazonaws.com/role-arn': autoscalerRole.arn
        }
      }
    },
    awsRegion: 'us-east-1',
    autoDiscovery: {
      enabled: true,
      clusterName: config.clusterName
    }
  }
})
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-forwardauth@kubernetescrd
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /manageworker/
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.service.port }}
      - path: /manageworker
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.service.port }}
publishedService: "default/rpa-service-traefik"
```

### Affected product version(s)
v2.9.2

### Reproducing the issue
Posted most relevant bits above.  I can give give a Pulumi employee temp read access to the full repo and original terraform project  repo if needed
