### ISSUE TITLE
Support for arbitrary iam role mappings in aws-auth configmap 

### ISSUE THREAD

**Issue by VRanga000** [pulumi/pulumi-eks#568]
The [EKS Cluster class](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cluster.ts#L606) in pulumi-eks creates a resource for the aws-auth configmap in the k8s cluster, after creation/upgrade.
Currently, this configmap's contents can be influenced using the params `instanceRole`, `instanceRoles` and `userMappings`. 
The `instanceRoles` params gets translated into a list of role mappings for which the role is obtained from the instancerole in the supplied instanceRoles list, and the mapping is generated to allow worker nodes access to the cluster:
```
{
        roleArn: arn,
        username: "system:node:{{EC2PrivateDNSName}}",
        groups: ["system:bootstrappers", "system:nodes"],
    }
```  

We have use cases (which is likely not uncommon) where we need to add custom role mappings like these:
```yaml
    - rolearn: "arn:aws:iam::xxx:role/ApplicationOwner"
      username: ao:{{SessionName}}
      groups:
        - app-owner
    - rolearn: "arn:aws:iam::xxx:role/k8s-user"
      username: user:{{SessionName}}
      groups:
        - k8s-user
    - rolearn: "arn:aws:iam::xxx:role/k8s-read-only"
      username: ro:{{SessionName}}
      groups:
        - k8s-clusterwide-read-only
```

It would be great to add a param `roleMappings` to allow such role mappings to be inserted, and managed directly via pulumi, rather than using external / disparate tooling.
