### ISSUE TITLE
error: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by yasinntza** [pulumi/pulumi-eks#720]
### What happened?

I am using GitHub action while deploying the app. I removed all resources and tried to set up them again but I am experiencing 
![Screen Shot 2022-06-11 at 23 57 12](https://user-images.githubusercontent.com/102040624/173204632-aec50433-10a9-4b09-a800-4506eca535a3.png)
![Screen Shot 2022-06-12 at 01 21 47](https://user-images.githubusercontent.com/102040624/173206765-f1bc11b5-bcba-44b4-9226-31e05ece7930.png)

### Steps to reproduce

I will share my package.json and cluster files. You will get the same error while deploying the app to pulumi.

package.json
```json
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "latest",
        "typescript": "^3.7.5"
    },
    "dependencies": {
        "@pulumi/aws": "latest",
        "@pulumi/awsx": "latest",
        "@pulumi/docker": "latest",
        "@pulumi/eks": "latest",
        "@pulumi/kubernetes": "latest",
        "@pulumi/pulumi": "latest",
        "@pulumi/random": "latest",
        "@pulumi/tls": "latest"
    }
}
```

```ts
import * as awsx from '@pulumi/awsx';
import * as eks from '@pulumi/eks';
import * as k8s from '@pulumi/kubernetes';
import * as aws from '@pulumi/aws';

const clusterAdminRoleName = 'clusterAdminRole';

const allowedUsersForK8SCluster: aws.iam.PolicyStatement[] = [];

const clusterAdminRoleEKSFullAccessPolicyStatements: aws.iam.PolicyStatement[] =
  [
    {
      Effect: 'Allow',
      Action: ['eks:*'],
      Resource: '*',
    },
    {
      Effect: 'Allow',
      Action: 'iam:PassRole',
      Resource: '*',
      Condition: {
        StringEquals: {
          'iam:PassedToService': 'eks.amazonaws.com',
        },
      },
    },
    {
      Effect: 'Allow',
      Action: ['iam:List*'],
      Resource: '*',
    },
  ];

const clusterAdminRole = new aws.iam.Role(clusterAdminRoleName, {
  inlinePolicies: [
    {
      name: 'EKS_Full_Access',
      policy: JSON.stringify({
        Version: '2012-10-17',
        Statement: [...clusterAdminRoleEKSFullAccessPolicyStatements],
      }),
    },
  ],
  assumeRolePolicy: {
    Version: '2012-10-17',
    Statement: [...allowedUsersForK8SCluster],
  },
  tags: {
    clusterAccess: `${clusterAdminRoleName}-user`,
  },
});

export const vpc = new awsx.ec2.Vpc(`app-vpc`, {
  numberOfAvailabilityZones: 2,
});

const eksClusterAdminRoleMapping: eks.RoleMapping = {
  groups: ['system:masters'],
  roleArn: clusterAdminRole.arn,
  username: 'pulumi:admin-user',
};

export const cluster = new eks.Cluster('k8-cluster', {
  name: 'k8-cluster',
  vpcId: vpc.id,
  publicSubnetIds: vpc.publicSubnetIds,
  privateSubnetIds: vpc.privateSubnetIds,
  instanceType: 't2.small',
  desiredCapacity: 2,
  minSize: 1,
  maxSize: 3,
  storageClasses: 'gp2',
  deployDashboard: false,
  roleMappings: [eksClusterAdminRoleMapping],
});

export const namespaceName = 'default';

// Grant cluster admin access to all admins with k8s ClusterRole and ClusterRoleBinding
const role = new k8s.rbac.v1.ClusterRole(
  'clusterAdminRole',
  {
    metadata: {
      name: 'clusterAdminRole',
      namespace: namespaceName,
    },
    rules: [
      {
        apiGroups: ['*'],
        resources: ['*'],
        verbs: ['*'],
      },
    ],
  },
  { provider: cluster.provider }
);

new k8s.rbac.v1.ClusterRoleBinding(
  'cluster-admin-binding',
  {
    metadata: {
      name: 'cluster-admin-binding',
    },
    subjects: [
      {
        kind: 'User',
        name: eksClusterAdminRoleMapping.username,
      },
    ],
    roleRef: {
      kind: 'ClusterRole',
      name: role.metadata.name,
      apiGroup: 'rbac.authorization.k8s.io',
    },
  },
  { provider: cluster.provider }
);

// Export the Cluster's Kubeconfig
export const kubeconfig = cluster.kubeconfig;

export const urn = cluster.urn;

```

### Expected Behavior

I should be able to deploy my app successfully.

### Actual Behavior

I got an error that I mention in `What Happened?` section.

### Versions used
```
CLI          
Version      3.34.1
Go Version   go1.18.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.8.0
docker      3.2.0
eks         0.40.0
kubernetes  3.19.3
nodejs      unknown
random      4.8.0
tls         4.6.0

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/myuser/.nvm/versions/node/v12.22.0/bin/node' version='v12.22.0'

Current Stack: staging

TYPE                                                        URN
I removed resource information.


Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/yasinntza
User           yasinntza
Organizations  yasinntza

Dependencies:
NAME                VERSION
@pulumi/aws         5.8.0
@pulumi/awsx        0.40.0
@pulumi/docker      3.2.0
@pulumi/eks         0.40.0
@pulumi/kubernetes  3.19.3
@pulumi/pulumi      3.34.1
@pulumi/random      4.8.0
@pulumi/tls         4.6.0
@types/node         17.0.42
typescript          3.9.10

Pulumi locates its logs in /var/folders/yl/n1dpjgm50csfyc_p79q_jz040000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by yasinntza** [comment]
I got another error.

![Screen Shot 2022-06-13 at 11 34 27](https://user-images.githubusercontent.com/102040624/173313373-ae38faf4-b29d-4bfd-afcc-dbf36958947e.png)

**Comment by yasinntza** [comment]
I created a new AWS account and tried to deploy the same app and there is no error for the new AWS account. I think I should do something in my AWS account.

**Comment by presidenten** [comment]
I think it has to do with that `CustomResourceDefinition` has gone to api version `v1`, and removed `v1beta1` from kubernetes 1.22, which is now the default kubernetes version in eks.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

```
Migrate manifests and API clients to use the apiextensions.k8s.io/v1 API version, available since v1.16.
```

**Comment by presidenten** [comment]
Ahh never mind. Updating to newer @pulumi/eks version solves it for me. (Currently using ^0.40.0)

**Comment by viveklak** [comment]
@yasinntza looks like you removed some resource information. Any chance this is an existing older cluster? The URNs in the resource information would have helped. It also appears you are running an older version of aws-cli (for the `client.authentication.k8s.io/v1alpha1` error). Please make sure you are running the latest aws-cli and kubectl.

**Comment by mlarose** [comment]
I have the same issue upgrading an existing EKS cluster's pulumi dependencies after a Kubernetes upgrade to 1.22. 

Starting from a fresh agent, using pulumi cli at 0.34.1 and a typescript, both the @pulumi/eks and its corresponding resource plugin are installed to 0.40.0 so that the [cni template](https://github.com/pulumi/pulumi-eks/blob/v0.40.0/nodejs/eks/cni/aws-k8s-cni.yaml#L202) use apiextensions.k8s.io/v1 instead of v1beta. 

But, running pulumi up in a CI/CD context, I still get the error reported by original poster (no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"). 

Investigating this, I noticed that, `pulumi up` will install the old version of pulumi-eks at version 0.33.0, as well as other older resource plugins. What I've found is that there is a reference in my state file to each of these installation: 

```
% pulumi stack export -s STACK | jq '.deployment.resources[] | select (.type == "pulumi:providers:eks")'
{
  "urn": "urn:pulumi:xxxxxxx::compute::pulumi:providers:eks::default",
  "custom": true,
  "id": "zzzzzzzzz",
  "type": "pulumi:providers:eks",
  "inputs": {
    "version": "0.33.0"
  },
  "outputs": {
    "version": "0.33.0"
  }
}
```

I found this while looking for a cleaner solution than editing the state i/o to version 0.40.0.

**Comment by yasinntza** [comment]
Update: These changes solved the `VpcCni` issue.
![Screen Shot 2022-06-15 at 12 22 54](https://user-images.githubusercontent.com/102040624/173792955-64078986-2b34-4d0d-8178-ff522f1e47dc.png)

**Comment by viveklak** [comment]
@Dysproz you need to use at least v0.39.0 of pulumi-eks. EKS has switched v1.22 as the default kubernetes version which doesn't have CRD supported in the v1beta1 endpoint - see https://github.com/pulumi/pulumi-eks/issues/720#issuecomment-1155351469.

We moved to using v1 in https://github.com/pulumi/pulumi-eks/pull/693 which fixes this problem.

**Comment by MayureshGharat** [comment]
I started seeing this issue recently. My dependencies look like these: 
```
  "dependencies": {
    "@pulumi/aws": "^5.8.0",
    "@pulumi/awsx": "^0.40.0",
    "@pulumi/eks": "^0.41.0",
    "@pulumi/kubernetes": "^3.21.0",
    "@pulumi/pulumi": "^3.34.1"
  },
```
This is the error:
```
Diagnostics:
  eks:index:VpcCni (cache-workloads-eks-prod-vpc-cni):
    error: Command failed: kubectl apply -f /var/folders/t6/zryv0n4s6wd5w39k8kqt8f880000gn/T/tmp-85433AsAoeTT8qUo5.tmp
    error: resource mapping not found for name: "eniconfigs.crd.k8s.amazonaws.com" namespace: "" from "/var/folders/t6/zryv0n4s6wd5w39k8kqt8f880000gn/T/tmp-85433AsAoeTT8qUo5.tmp": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
    ensure CRDs are installed first

  pulumi:pulumi:Stack (eks-eks-prod):
    error: resource mapping not found for name: "eniconfigs.crd.k8s.amazonaws.com" namespace: "" from "/var/folders/t6/zryv0n4s6wd5w39k8kqt8f880000gn/T/tmp-85433AsAoeTT8qUo5.tmp": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
    ensure CRDs are installed first

    error: update failed
```

cat /var/folders/t6/zryv0n4s6wd5w39k8kqt8f880000gn/T/tmp-85433AsAoeTT8qUo5.tmp
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-node
rules:
  - apiGroups:
      - crd.k8s.amazonaws.com
    resources:
      - eniconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
      - update
  - apiGroups:
      - extensions
    resources:
      - '*'
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-node
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-node
subjects:
  - kind: ServiceAccount
    name: aws-node
    namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: aws-node
  namespace: kube-system
  labels:
    k8s-app: aws-node
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      labels:
        k8s-app: aws-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
      containers:
        - env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WARM_ENI_TARGET
              value: '1'
            - name: AWS_VPC_K8S_CNI_LOGLEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_CNI_LOG_FILE
              value: /host/var/log/aws-routed-eni/ipamd.log
            - name: AWS_VPC_K8S_CNI_VETHPREFIX
              value: eni
            - name: AWS_VPC_ENI_MTU
              value: '9001'
            - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
              value: /var/log/aws-routed-eni/plugin.log
            - name: ENABLE_POD_ENI
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
              value: 'false'
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: 'false'
          image: '602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.7.5'
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - '-addr=:50051'
            initialDelaySeconds: 60
          name: aws-node
          ports:
            - containerPort: 61678
              name: metrics
          readinessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - '-addr=:50051'
            initialDelaySeconds: 1
          resources:
            requests:
              cpu: 10m
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /host/var/log/aws-routed-eni
              name: log-dir
            - mountPath: /var/run/aws-node
              name: run-dir
            - mountPath: /var/run/dockershim.sock
              name: dockershim
            - mountPath: /run/xtables.lock
              name: xtables-lock
      hostNetwork: true
      initContainers:
        - env:
            - name: DISABLE_TCP_EARLY_DEMUX
              value: 'false'
          image: >-
            602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.7.5
          imagePullPolicy: Always
          name: aws-vpc-cni-init
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
      priorityClassName: system-node-critical
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin-dir
        - hostPath:
            path: /etc/cni/net.d
          name: cni-net-dir
        - hostPath:
            path: /var/run/dockershim.sock
          name: dockershim
        - hostPath:
            path: /run/xtables.lock
          name: xtables-lock
        - hostPath:
            path: /var/log/aws-routed-eni
            type: DirectoryOrCreate
          name: log-dir
        - hostPath:
            path: /var/run/aws-node
            type: DirectoryOrCreate
          name: run-dir
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
cat /var/folders/t6/zryv0n4s6wd5w39k8kqt8f880000gn/T/tmp-85433AsAoeTT8qUo5.tmp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-node
rules:
  - apiGroups:
      - crd.k8s.amazonaws.com
    resources:
      - eniconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
      - update
  - apiGroups:
      - extensions
    resources:
      - '*'
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-node
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-node
subjects:
  - kind: ServiceAccount
    name: aws-node
    namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: aws-node
  namespace: kube-system
  labels:
    k8s-app: aws-node
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      labels:
        k8s-app: aws-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
      containers:
        - env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WARM_ENI_TARGET
              value: '1'
            - name: AWS_VPC_K8S_CNI_LOGLEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_CNI_LOG_FILE
              value: /host/var/log/aws-routed-eni/ipamd.log
            - name: AWS_VPC_K8S_CNI_VETHPREFIX
              value: eni
            - name: AWS_VPC_ENI_MTU
              value: '9001'
            - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
              value: /var/log/aws-routed-eni/plugin.log
            - name: ENABLE_POD_ENI
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
              value: 'false'
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: 'false'
          image: '602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.7.5'
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - '-addr=:50051'
            initialDelaySeconds: 60
          name: aws-node
          ports:
            - containerPort: 61678
              name: metrics
          readinessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - '-addr=:50051'
            initialDelaySeconds: 1
          resources:
            requests:
              cpu: 10m
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /host/var/log/aws-routed-eni
              name: log-dir
            - mountPath: /var/run/aws-node
              name: run-dir
            - mountPath: /var/run/dockershim.sock
              name: dockershim
            - mountPath: /run/xtables.lock
              name: xtables-lock
      hostNetwork: true
      initContainers:
        - env:
            - name: DISABLE_TCP_EARLY_DEMUX
              value: 'false'
          image: >-
            602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.7.5
          imagePullPolicy: Always
          name: aws-vpc-cni-init
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
      priorityClassName: system-node-critical
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin-dir
        - hostPath:
            path: /etc/cni/net.d
          name: cni-net-dir
        - hostPath:
            path: /var/run/dockershim.sock
          name: dockershim
        - hostPath:
            path: /run/xtables.lock
          name: xtables-lock
        - hostPath:
            path: /var/log/aws-routed-eni
            type: DirectoryOrCreate
          name: log-dir
        - hostPath:
            path: /var/run/aws-node
            type: DirectoryOrCreate
          name: run-dir
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
```
