### ISSUE TITLE
EKS security group created in the wrong VPC

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-eks#767]
### What happened?

I created a YAML program to create a new VPC and an EKS cluster in that new VPC. `pulumi preview` does not report any errors or issues, but when running `pulumi up` an error is returned that a security group was created in a different VPC.

Here's the YAML program (apparently YAML isn't supported to attach?):

```yaml
name: k8s-aws-yaml
runtime: yaml
description: A Pulumi YAML program to stand up a Kubernetes cluster on AWS
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
configuration:
  minClusterSize:
    type: Number
    default: 3
  maxClusterSize:
    type: Number
    default: 6
  desiredClusterSize:
    type: Number
    default: 3
  eksNodeInstanceType:
    type: String
    default: t2.medium
  vpcNetworkCidr:
    type: String
    default: 10.0.0.0/16
resources:
  # Create a VPC for the EKS cluster
  eks-vpc:
    type: awsx:ec2:Vpc
    properties:
      enableDnsHostnames: true
      cidrBlock: ${vpcNetworkCidr}
  # Create the EKS cluster
  eks-cluster:
    type: eks:Cluster
    properties:
      # Put the cluster in the new VPC created earlier
      vpcId: ${eks-vpc.id}
      # Public subnets will be used for load balancers
      publicSubnetIds: ${eks-vpc.publicSubnetIds}
      # Private subnets will be used for cluster nodes
      privateSubnetIds: ${eks-vpc.privateSubnetIds}
      # Change configuration section above to change any of the following settings
      instanceType: ${eksNodeInstanceType}
      desiredCapacity: ${desiredClusterSize}
      minSize: ${minClusterSize}
      maxSize: ${maxClusterSize}
      # Do not give the worker nodes public IP addresses
      nodeAssociatePublicIpAddress: false
outputs:
  # Output the Kubeconfig for the cluster
  kubeconfig: ${eks-cluster.kubeconfig}
  vpcId: ${eks-vpc.id}
```

I've attached a screenshot of the error:

<img width="762" alt="Screen Shot 2022-08-26 at 2 06 57 PM" src="https://user-images.githubusercontent.com/1977326/186979386-252de770-97f1-4d00-9b84-4ea01d64cce5.png">

I have verified, using the AWS CLI, that the referenced security group does indeed get created in a different VPC than the one created in the YAML program (I have not verified if it is putting it in the default VPC, but that seems likely given the short ID on the VPC.)

### Steps to reproduce

1. Create a Pulumi program that creates a new VPC and attempts to create an EKS cluster in that new VPC.
2. Observe the error.

### Expected Behavior

I expected the EKS cluster and all associated resources to be created in the correct VPC.

### Actual Behavior

A security group required by the EKS cluster gets created in a different VPC than the one specified.

### Output of `pulumi about`

CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
awsx  unknown
eks   unknown
yaml  unknown

Host
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in yaml

Current Stack: us-east-2

Found no resources associated with us-east-2

Found no pending operations associated with us-east-2

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

No dependencies found

Pulumi locates its logs in /var/folders/c_/1pdwtg4j5zx4dvx5t6qp9v180000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment]
This isn't actually an issue with EKS, it's a behaviour problem with Pulumi YAML

In this program, the output is incorrect, it should be
```yaml
vpcId: ${eks-vpc.vpcId}
```

Because the output is wrong, it’s essentially nil. `eks` then creates the cluster in the default security group, and the nodes in the subnets you’ve defined

Ideally, pulumi yaml should tell you that

```yaml
vpcId: ${eks-vpc.id}
```

Is nil, but it doesn’t

This works:

```yaml
name: k8s-aws-yaml
runtime: yaml
description: A Pulumi YAML program to stand up a Kubernetes cluster on AWS
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
configuration:
  minClusterSize:
    type: Number
    default: 3
  maxClusterSize:
    type: Number
    default: 6
  desiredClusterSize:
    type: Number
    default: 3
  eksNodeInstanceType:
    type: String
    default: t2.medium
  vpcNetworkCidr:
    type: String
    default: 10.0.0.0/16
resources:
  # Create a VPC for the EKS cluster
  vpc:
    type: awsx:ec2:Vpc
    properties:
      enableDnsHostnames: true
      cidrBlock: ${vpcNetworkCidr}
  # Create the EKS cluster
  cluster:
    type: eks:Cluster
    properties:
      # Put the cluster in the new VPC created earlier
      vpcId: ${vpc.vpcId}
      # Public subnets will be used for load balancers
      publicSubnetIds: ${vpc.publicSubnetIds}
      # Private subnets will be used for cluster nodes
      privateSubnetIds: ${vpc.privateSubnetIds}
      # Change configuration section above to change any of the following settings
      instanceType: ${eksNodeInstanceType}
      desiredCapacity: ${desiredClusterSize}
      minSize: ${minClusterSize}
      maxSize: ${maxClusterSize}
      # Do not give the worker nodes public IP addresses
      nodeAssociatePublicIpAddress: false
outputs:
  # Output the Kubeconfig for the cluster
  kubeconfig: ${cluster.kubeconfig}
  vpcId: ${vpc.vpcId}
  ```
  
  I think we need to move close this, and open an issue in pulumi YAML about nil outputs
