### ISSUE TITLE
Nodes fail to join cluster because aws-auth not updated

### ISSUE THREAD

**Issue by liam-j-bennett** [pulumi/pulumi-eks#883]
### What happened?

Following [this doc](https://www.pulumi.com/docs/clouds/aws/guides/eks/#configuring-your-eks-clusters-worker-nodes-and-node-groups), creating a nodegroup after the cluster is instantiated, the instances are created, but fail to join the cluster with:

```
time="2023-05-25T08:55:22Z" level=warning msg="access denied" arn="arn:aws:iam::640907157373:role/obs-node-role-bae465a" client="127.0.0.1:50308" error="ARN is not mapped" method=POST path=/authenticate
```

This occurs as the node role for that nodegroup is not added to `aws-auth-cm.yaml`. This happens using both `NewNodeGroup` and `NewNodeGroupV2` functions.

Adding that role to the `aws-auth-cm` fixes the issue.

### Expected Behavior

I expect the `NewNodeGroup` or `NewNodeGroupV2` to update the `aws-auth-cm.yaml` with the node role of the new nodegroup, or the document needs to specify a patch that needs to be applied by the Kubernetes provider.

### Steps to reproduce

1. Create a EKS cluster
```
eksVpc, err := ec2.NewVpc(ctx, "eks-vpc", &ec2.VpcArgs{
			EnableDnsHostnames: pulumi.Bool(true),
			CidrBlock:          &vpcNetworkCidr,
		})
		if err != nil {
			return err
		}

		eksCluster, err := eks.NewCluster(ctx, "eks-cluster", &eks.ClusterArgs{
			VpcId:                        eksVpc.VpcId,
			PublicSubnetIds:              eksVpc.PublicSubnetIds,
			PrivateSubnetIds:             eksVpc.PrivateSubnetIds,
			NodeAssociatePublicIpAddress: pulumi.BoolRef(false),
			RoleMappings: eks.RoleMappingArray{
				eks.RoleMappingArgs{
					Groups: pulumi.StringArray{
						pulumi.String("system:masters"),
					},
					RoleArn:  pulumi.String(opsPrincipalRole),
					Username: pulumi.String("ops-user"),
				},
			},
			InstanceType:    pulumi.String("t2.medium"),
			DesiredCapacity: pulumi.Int(3),
			MinSize:         pulumi.Int(1),
			MaxSize:         pulumi.Int(5),
			EnabledClusterLogTypes: pulumi.StringArray{
				pulumi.String("api"),
				pulumi.String("audit"),
				pulumi.String("authenticator"),
				pulumi.String("controllerManager"),
				pulumi.String("scheduler"),
			},
})
```
2. Create a Node Pool
```
managedPolicyArns := []string{
			"arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
			"arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
			"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
		}
		tmpJSON0, err := json.Marshal(map[string]interface{}{
			"Version": "2012-10-17",
			"Statement": []map[string]interface{}{
				{
					"Action": "sts:AssumeRole",
					"Effect": "Allow",
					"Sid":    "",
					"Principal": map[string]interface{}{
						"Service": "ec2.amazonaws.com",
					},
				},
			},
		})
		if err != nil {
			return err
		}
		json0 := string(tmpJSON0)
		assumeRolePolicy := json0
		obsRole, err := iam.NewRole(ctx, "obs-node-role", &iam.RoleArgs{
			AssumeRolePolicy:  pulumi.String(assumeRolePolicy),
			ManagedPolicyArns: pulumi.ToStringArray(managedPolicyArns),
		})
		if err != nil {
			return err
		}
		obsIP, err := iam.NewInstanceProfile(ctx, "obs-node-instance-profile", &iam.InstanceProfileArgs{
			Role: obsRole.Name,
		})
		if err != nil {
			return err
		}

		// This fails with NodeGroup and NodegroupV2
		_, err = eks.NewNodeGroup(ctx, "observability-nodes", &eks.NodeGroupArgs{
			Cluster:         eksCluster,
			InstanceType:    pulumi.String("t2.medium"),
			DesiredCapacity: pulumi.Int(1),
			MinSize:         pulumi.Int(1),
			MaxSize:         pulumi.Int(3),
			InstanceProfile: obsIP,
		})
```
3. See the nodes are not joining
4. Look at AWS Logs and see error
```
time="2023-05-25T08:55:22Z" level=warning msg="access denied" arn="arn:aws:iam::640907157373:role/obs-node-role-bae465a" client="127.0.0.1:50308" error="ARN is not mapped" method=POST path=/authenticate
```

### Output of `pulumi about`

Using
```
github.com/pulumi/pulumi-aws/sdk/v5         5.41.0
github.com/pulumi/pulumi-awsx/sdk           1.0.2
github.com/pulumi/pulumi-eks/sdk            1.0.2
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.28.0
github.com/pulumi/pulumi/sdk/v3             3.68.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hey @liam-j-bennett thank you for reporting this issue.

I'm looking at it but I'm not super fluent with EKS and will need to do my homework. When you say

> Adding that role to the aws-auth-cm fixes the issue.

What exactly did you do to fix it?

**Comment by liam-j-bennett** [comment]
Apologies for the late reply, I've been on annual leave.

> I'm looking at it but I'm not super fluent with EKS

Same, unfortunately. So I had to do some digging myself and figured this was the problem.

The EKS cluster gets created with a `aws-auth` configmap that maps IAM roles to Kubernetes RBAC and defines which nodes can join and which users have access etc. (see https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html#aws-auth-configmap). It looks something like this:

```
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<SOME-ARN>
      username: ops-user
      groups:
        - system:masters
    - rolearn: arn:aws:iam::640907157373:role/eks-cluster-instanceRole-role-c4e70bf
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: aws-auth
  namespace: kube-system
```



When creating a cluster, this gets controlled by the `RoleMappings` argument. In the example, I add a 'master' user that maps to an IAM role, which you can see in the ConfigMap above (I redacted the ARN itself):

```
eksCluster, err := eks.NewCluster(ctx, "eks-cluster", &eks.ClusterArgs{
...
			RoleMappings: eks.RoleMappingArray{
				eks.RoleMappingArgs{
					Groups: pulumi.StringArray{
						pulumi.String("system:masters"),
					},
					RoleArn:  pulumi.String(opsPrincipalRole),
					Username: pulumi.String("ops-user"),
				},
			},
...
```

Essentially, when creating the `NodeGroup` via non-managed calls (e.g. `eks.NewNodeGroupV2()`) the node role ARN isn't added to this configmap. So the fix is to edit the ConfigMap to add the role the new nodes are using (I used pulumi to patch the configmap after the node was created), so you'd end up with:

``````
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<SOME-ARN>
      username: ops-user
      groups:
        - system:masters
    - rolearn: arn:aws:iam::640907157373:role/eks-cluster-instanceRole-role-c4e70bf
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
     - rolearn: arn:aws:iam::640907157373:role/eks-cluster-new-instance-role-blahid
        username: system:node:{{EC2PrivateDNSName}}
        groups:
          - system:bootstrappers
          - system:nodes
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: aws-auth
  namespace: kube-system
```

After this patch, the node can join successfully.
