### ISSUE TITLE
Default vpc cni version upgrade

### ISSUE THREAD

**Issue by balticore** [pulumi/pulumi-eks#924]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, [default vpc cni version tag](https://github.com/pulumi/pulumi-eks/blob/92b885d7bae98030ea1534c938b5e11818c35f3e/nodejs/eks/cni/aws-k8s-cni.yaml#L100) is `amazon-k8s-cni:v1.11.0`, but for EKS version 1.25+ [recommendations](https://github.com/aws/amazon-vpc-cni-k8s#recommended-version) are to have VPC CNI version v1.11.4+. Also mentioned in [AWS EKS 1.26 blogpost](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/)

Is there a plan to have the default version bumped or maybe there is some reason why it is kept at current version such as compatibility?

If it is ready to be bumped I would not mind helping with that.

### Affected area/feature

When we upgrade EKS clusters with Pulumi, VPC CNI version remains at default version.

**Comment by mikhailshilkov** [comment]
@balticore I don't think there is a particular reason for that. We'd welcome your contribution to bump it up.

**Comment by balticore** [comment]
In that case I would like to try to help

**Comment by mikhailshilkov** [comment]
@balticore Feel free to open a PR and reference this issue from its description, we'll get it reviewed and merged.

**Comment by balticore** [comment]
I have attempted to bump the version and modify https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cni/aws-k8s-cni.yaml:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: aws-node
    labels:
        app.kubernetes.io/name: aws-node
        app.kubernetes.io/instance: aws-vpc-cni
        k8s-app: aws-node
        app.kubernetes.io/version: "v1.13.4"
rules:
    - apiGroups:
          - crd.k8s.amazonaws.com
      resources:
          - eniconfigs
      verbs:
          - get
          - list
          - watch
    - apiGroups: [""]
      resources:
          - pods
          - namespaces
      verbs: ["list", "watch", "get"]
    - apiGroups: [""]
      resources:
          - nodes
      verbs:
          - list
          - watch
          - get
          - update
    - apiGroups: [ "", "events.k8s.io" ]
      resources:
          - events
      verbs: [ "create", "patch", "list" ]

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: aws-node
    namespace: kube-system
    labels:
        app.kubernetes.io/name: aws-node
        app.kubernetes.io/instance: aws-vpc-cni
        k8s-app: aws-node
        app.kubernetes.io/version: "v1.13.4"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: aws-node
    labels:
        app.kubernetes.io/name: aws-node
        app.kubernetes.io/instance: aws-vpc-cni
        k8s-app: aws-node
        app.kubernetes.io/version: "v1.13.4"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: aws-node
subjects:
    - kind: ServiceAccount
      name: aws-node
      namespace: kube-system

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
    name: aws-node
    namespace: kube-system
    labels:
        app.kubernetes.io/name: aws-node
        app.kubernetes.io/instance: aws-vpc-cni
        k8s-app: aws-node
        app.kubernetes.io/version: "v1.13.4"
spec:
    updateStrategy:
        rollingUpdate:
            maxUnavailable: 10%
        type: RollingUpdate
    selector:
        matchLabels:
            k8s-app: aws-node
    template:
        metadata:
            labels:
                app.kubernetes.io/name: aws-node
                app.kubernetes.io/instance: aws-vpc-cni
                k8s-app: aws-node
        spec:
            priorityClassName: "system-node-critical"
            serviceAccountName: aws-node
            hostNetwork: true
            initContainers:
                - name: aws-vpc-cni-init
                  image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.13.4"
                  env: []
                  securityContext:
                      privileged: true
                  resources:
                      requests:
                          cpu: 25m
                  volumeMounts:
                      - mountPath: /host/opt/cni/bin
                        name: cni-bin-dir
            terminationGracePeriodSeconds: 10
            tolerations:
                - operator: Exists
            securityContext: {}
            containers:
                - name: aws-node
                  image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.13.4"
                  ports:
                      - containerPort: 61678
                        name: metrics
                  livenessProbe:
                      exec:
                          command:
                              - /app/grpc-health-probe
                              - -addr=:50051
                              - -connect-timeout=5s
                              - -rpc-timeout=5s
                      initialDelaySeconds: 60
                      timeoutSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - /app/grpc-health-probe
                              - -addr=:50051
                              - -connect-timeout=5s
                              - -rpc-timeout=5s
                      initialDelaySeconds: 1
                      timeoutSeconds: 10
                  env:
                      - name: ADDITIONAL_ENI_TAGS
                        value: "{}"
                      - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
                        value: "prng"
                      - name: DISABLE_INTROSPECTION
                        value: "false"
                      - name: DISABLE_METRICS
                        value: "false"
                      - name: DISABLE_NETWORK_RESOURCE_PROVISIONING
                        value: "false"
                      - name: WARM_PREFIX_TARGET
                        value: "1"
                      - name: MY_NODE_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.nodeName
                      -   name: MY_POD_NAME
                          valueFrom:
                              fieldRef:
                                  apiVersion: v1
                                  fieldPath: metadata.name
                  resources:
                      requests:
                          cpu: 25m
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                              - NET_RAW
                  volumeMounts:
                      - mountPath: /host/opt/cni/bin
                        name: cni-bin-dir
                      - mountPath: /host/etc/cni/net.d
                        name: cni-net-dir
                      - mountPath: /host/var/log/aws-routed-eni
                        name: log-dir
                      - mountPath: /var/run/aws-node
                        name: run-dir
                      - mountPath: /run/xtables.lock
                        name: xtables-lock
            volumes:
                - name: cni-bin-dir
                  hostPath:
                      path: /opt/cni/bin
                - name: cni-net-dir
                  hostPath:
                      path: /etc/cni/net.d
                - name: log-dir
                  hostPath:
                      path: /var/log/aws-routed-eni
                      type: DirectoryOrCreate
                - name: run-dir
                  hostPath:
                      path: /var/run/aws-node
                      type: DirectoryOrCreate
                - name: xtables-lock
                  hostPath:
                      path: /run/xtables.lock
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: kubernetes.io/os
                                    operator: In
                                    values:
                                        - linux
                                  - key: kubernetes.io/arch
                                    operator: In
                                    values:
                                        - amd64
                                        - arm64
                                  - key: eks.amazonaws.com/compute-type
                                    operator: NotIn
                                    values:
                                        - fargate
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: eniconfigs.crd.k8s.amazonaws.com
    labels:
        app.kubernetes.io/name: aws-node
        app.kubernetes.io/instance: aws-vpc-cni
        k8s-app: aws-node
spec:
    scope: Cluster
    group: crd.k8s.amazonaws.com
    preserveUnknownFields: false
    versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
    names:
        plural: eniconfigs
        singular: eniconfig
        kind: ENIConfig

```

Simply bumping version directly in Daemonset pulled the correct image version `amazon-k8s-cni:v1.13.4`, however when I try testing it by linking yarn dependency it does not seem to pick up local version.

What I did to test it:

1. Modify https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cni/aws-k8s-cni.yaml and applied changes in yaml above.

2. Run 
```bash
$ make build_nodejs && make install_nodejs_sdk
```
This seem to create a link which I can also find in yarn config folder.

4. Go to Pulumi project directory and run
```bash
yarn link @pulumi/eks
```
In `node_modules` folder I can find correctly linked @pulumi/eks dependency with applied changes on `aws-k8s-cni.yaml`. Also I can see the linked version in `node_modules/@pulumi/eks/package.json`

```json
{
    "name": "@pulumi/eks",
    "version": "v1.1.0-alpha.1696970025+92b885d7.dirty",
    "description": "Pulumi Amazon Web Services (AWS) EKS Components.",
    "license": "Apache-2.0",
    "keywords": [
        "pulumi",
        "aws",
        "eks"
    ],
    "scripts": {
        "format": "prettier --list-different --write ."
    },
    "homepage": "https://pulumi.com",
    "repository": {
        "type": "git",
        "url": "https://github.com/pulumi/pulumi-eks.git"
    },
    "bugs": "https://github.com/pulumi/pulumi-eks/issues",
    "dependencies": {
        "@pulumi/aws": "5.31.0",
        "@pulumi/kubernetes": "^3.20.2",
        "@pulumi/pulumi": "^3.47.0",
        "https-proxy-agent": "^5.0.1",
        "js-yaml": "^4.1.0",
        "netmask": "^2.0.2",
        "semver": "^7.3.7",
        "which": "^1.3.1"
    },
    "devDependencies": {
        "@types/js-yaml": "^4.0.5",
        "@types/netmask": "^1.0.30",
        "@types/node": "^18.11.13",
        "@types/semver": "^7.3.10",
        "@types/which": "^1.3.1",
        "pkg": "^5.8.0",
        "prettier": "^2.8.1",
        "tslint": "^6.1.3",
        "tslint-config-prettier": "^1.18.0",
        "typescript": "^3.7.0"
    },
    "pulumi": {
        "resource": true
    },
    "prettier": {
        "tabWidth": 4,
        "trailingComma": "all",
        "printWidth": 100
    }
}
```

I then specify the linked version in Pulumi project package.json

```json
{
    "name": "eks-cluster-test",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^16"
    },
    "dependencies": {
        "@pulumi/pulumi": "^3.0.0",
        "@pulumi/awsx": "1.0.2",
        "@pulumi/eks": "v1.1.0-alpha.1696970025+92b885d7.dirty"
    }
}
```

After running `yarn install` I do `pulumi up` and EKS cluster is created. However, it still picks up upstream `aws-k8s-cni` version `1.11.0`. I have tried clearing yarn cache and yarn links folder and even resorted to create fresh pulumi project but no matter what it still picks up upstream version specified in this repo but not local one which should be `1.13.4`. I am reluctant to create PR before I can actually test this. I have also tried running integration tests but they seem very slow and it's not feasible to run after each change of configuration, so simply spinning up pulumi eks cluster would be much preferred. I don't mind running integration tests once I verify that changes are applied correctly.

Maybe someone else have experienced similar issue before?
